### ISSUE TITLE
Keyboard key colors are not cached

### ISSUE THREAD

**Issue by roj1512** [Hugo0/wordle#10]
The keyboard key colors are not cached in `localStorage`.

If the user refreshes the page, the keyboard key colors which are indicating their existence in the Wordle, will not recover.

**Comment by Hugo0** [comment]
Yeah this is an issue I noticed too. I don't have the time to work on it right now unfortunately, but in principle it should be fairly simple I think

**Comment by Hugo0** [comment]
@roj1512 Found some time to work on this, ended up being relatively simple, it's fixed now!

Cheers
