### ISSUE TITLE
 Low German (nds)

### ISSUE THREAD

**Issue by rwmpelstilzchen** [Hugo0/wordle#13]
I think [Low German](https://en.wikipedia.org/wiki/Low_German) ([nds](https://iso639-3.sil.org/code/nds); [Plattdüütsch](https://nds.wikipedia.org/wiki/Plattd%C3%BC%C3%BCtsch)) is titled ‘Latgalian’ by mistake.

I found this while adding Wordle Global entries to [Wordles of the World](https://rwmpelstilzchen.gitlab.io/wordles/). The changes will be up soon.

Wordle Global is very impressive 👍. AFAIK this is the most translated/localised (albeit machine-translated in most cases, if I’m not mistaken) version.

**Comment by Hugo0** [comment]
Thanks @rwmpelstilzchen ! Was fun to work on, and it's great to see so many people use it (~5k per day!).

I took a look, you're totally right, not sure how that happened. I've renamed it now: www.wordle.global/nds
