### ISSUE TITLE
Mistakes in Estonian Wordle

### ISSUE THREAD

**Issue by Lea0011** [Hugo0/wordle#14]
The keyboard for Estonian Wordles is not right, it misses some vowels, like  Ü and Õ. And Å is not needed in Estonian.

**Comment by Hugo0** [comment]
Huh, interesting. I changed it as per your suggestions, tell me if it's okay now 

wordle.global/et

if not you can also just edit this file:
https://github.com/Hugo0/wordle/blob/main/webapp/data/languages/et/et_keyboard.json 
And change the order of the letters (or add new ones)

Cheers!

**Comment by Lea0011** [comment]
Thanks, it's ok now, all letters are available. The order is a bit unusual,
but I think it doesn't matter much.

Waiting for tomorrow 😉

Lea
