### ISSUE TITLE
Swedish wordlist

### ISSUE THREAD

**Issue by arildm** [Hugo0/wordle#22]
The typical wordlist to use for word games is Svenska akademiens ordlista (SAOL; [search](https://svenska.se/saol/), [info in Swedish](https://www.svenskaakademien.se/svenska-spraket/svenska-akademiens-ordlista-saol)), but it is not free to use in software.

An alternative, free resource is [SALDO](https://spraakbanken.gu.se/resurser/saldo), which is compiled by Språkbanken at the University of Gothenburg (disclaimer: I work there as a research engineer). To get a glimpse of the content, five-letter words can be browsed [here](https://spraakbanken.gu.se/karp/#?mode=saldo&lang=eng&advanced=false&searchTab=special&hpp=25&extended=and%7Cbaseform%7Cregexp%7C.....%7C%7Cand%7Cpos%7Cequals%7Cnn%7Cav%7Cvb%7Cab%7Cpp&page=1&resources=saldo,saldom,saldoe&search=extended%7C%7Cand%7Cbaseform%7Cregexp%7C.....%7C%7Cand%7Cpos%7Cequals%7Cnn%7Cav%7Cvb%7Cab%7Cpp&map=false).

I'll get a pull request going...

**Comment by arildm** [comment]
Pull request #23 ready for review!

**Comment by Hugo0** [comment]
thanks aril! merged!
