### ISSUE TITLE
Portuguese words

### ISSUE THREAD

**Issue by rmimessi** [Hugo0/wordle#24]
Hi, I don’t know if this vocabulary refers to Portugal or Brazilian portuguese, or both of them. The fact is that I am playing with Wordle in Brazil and faced with some words that do not belong to our vocabulary. This is frustrating, because after several hours trying to find the correct Word, we discover that it does not exist... and we lost our time for nothing !!! Sorry, but I consider this comment relevant for the community.

**Comment by Hugo0** [comment]
fixed, thanks @aspich
