### ISSUE TITLE
Is there an administrator who could put an end to this joke of a website?

### ISSUE THREAD

**Issue by DrWords** [Hugo0/wordle#75]

**Comment by Hugo0** [comment]
Hey @DrWords ! Sorry for your frustration, I really feel it. I haven't had time to dedicate to wordle.global, my job keeps me very busy and wordle is completely free (don't even have ads), so it's hard to justify putting in even more effort into it :(

If you have gripes with the word lists, you can modify the code yourself (it's all open source here on github!), and submit a [Pull Request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests). I'll approve your changes and they will go live on the website
